#!/bin/bash

echo "🔄 JSON Cookie'larni Netscape Formatiga O'tkazish"
echo "=================================================="
echo ""

cd ~/www/download.e-qarz.uz

COOKIES_DIR="storage/app/cookies"
mkdir -p "$COOKIES_DIR"

OUTPUT_FILE="$COOKIES_DIR/instagram_cookies.txt"

echo "📋 Qadam 1: JSON cookie'larni Netscape formatiga o'tkazish"
echo "----------------------------------------------------------"
echo ""

# JSON cookie'larni Netscape formatiga o'tkazish
cat > /tmp/convert_cookies.php << 'PHPEOF'
<?php
$json = file_get_contents('php://stdin');
$cookies = json_decode($json, true);

if (!$cookies) {
    fwrite(STDERR, "❌ JSON noto'g'ri!\n");
    exit(1);
}

// Netscape header
echo "# Netscape HTTP Cookie File\n";
echo "# This file was generated by converting JSON cookies\n";
echo "# Generated: " . date('Y-m-d H:i:s') . "\n";
echo "\n";

foreach ($cookies as $cookie) {
    $domain = $cookie['domain'] ?? '';
    $name = $cookie['name'] ?? '';
    $value = $cookie['value'] ?? '';
    $path = $cookie['path'] ?? '/';
    $expiration = isset($cookie['expirationDate']) ? (int)$cookie['expirationDate'] : 0;
    $secure = isset($cookie['secure']) && $cookie['secure'] ? 'TRUE' : 'FALSE';
    
    // Netscape format:
    // domain	flag	path	secure	expiration	name	value
    // flag is always TRUE for domain cookies
    $flag = 'TRUE';
    
    // Format: domain	flag	path	secure	expiration	name	value
    printf("%s\t%s\t%s\t%s\t%d\t%s\t%s\n", 
        $domain,
        $flag,
        $path,
        $secure,
        $expiration,
        $name,
        $value
    );
}
PHPEOF

echo "📝 JSON cookie'larni kiriting (Ctrl+D tugmasini bosing tugaganda):"
echo ""

# JSON'ni o'qish va konvertatsiya qilish
JSON_INPUT=$(cat)

if [ -z "$JSON_INPUT" ]; then
    echo "❌ JSON kiritilmadi!"
    echo ""
    echo "📋 Qanday ishlatish:"
    echo "   1. JSON cookie'larni ko'chirib oling"
    echo "   2. Quyidagi buyruqni bajaring:"
    echo ""
    echo "   echo 'YOUR_JSON_HERE' | ./CONVERT_COOKIES_JSON_TO_NETSCAPE.sh"
    echo ""
    exit 1
fi

# PHP orqali konvertatsiya qilish
echo "$JSON_INPUT" | php /tmp/convert_cookies.php > "$OUTPUT_FILE"

if [ $? -eq 0 ] && [ -f "$OUTPUT_FILE" ] && [ -s "$OUTPUT_FILE" ]; then
    echo "✅ Cookie fayli yaratildi: $OUTPUT_FILE"
    echo ""
    
    # Tekshirish
    echo "📋 Qadam 2: Cookie faylini tekshirish"
    echo "----------------------------------------------------------"
    echo ""
    
    SIZE=$(stat -f%z "$OUTPUT_FILE" 2>/dev/null || stat -c%s "$OUTPUT_FILE" 2>/dev/null)
    LINES=$(wc -l < "$OUTPUT_FILE" 2>/dev/null || echo "0")
    
    echo "   Fayl hajmi: ${SIZE} bytes"
    echo "   Qatorlar soni: ${LINES}"
    echo ""
    
    # Muhim cookie'larni tekshirish
    if grep -q "sessionid" "$OUTPUT_FILE" 2>/dev/null; then
        echo "   ✅ sessionid topildi"
    else
        echo "   ❌ sessionid topilmadi!"
    fi
    
    if grep -q "csrftoken" "$OUTPUT_FILE" 2>/dev/null; then
        echo "   ✅ csrftoken topildi"
    else
        echo "   ⚠️  csrftoken topilmadi"
    fi
    
    if grep -q "ds_user_id" "$OUTPUT_FILE" 2>/dev/null; then
        echo "   ✅ ds_user_id topildi"
    else
        echo "   ⚠️  ds_user_id topilmadi"
    fi
    
    echo ""
    echo "📄 Faylning birinchi 5 qatori:"
    head -5 "$OUTPUT_FILE"
    echo ""
    
    # Permissions
    chmod 600 "$OUTPUT_FILE"
    echo "✅ Permissions o'rnatildi (600)"
    echo ""
    
    echo "===================================="
    echo "✅ Tugadi!"
    echo ""
    echo "📋 Keyingi qadamlar:"
    echo "   1. Cookie faylini sozlash:"
    echo "      ./SETUP_MULTIPLE_COOKIES.sh"
    echo ""
    echo "   2. Yoki to'liq sozlash:"
    echo "      ./QUICK_COOKIE_SETUP.sh"
    echo ""
else
    echo "❌ Xato! Cookie fayli yaratilmadi"
    echo ""
    echo "📋 Muammo bo'lsa:"
    echo "   - JSON format to'g'ri ekanligini tekshiring"
    echo "   - PHP ishlayotganini tekshiring: php -v"
    exit 1
fi

# Temp faylni o'chirish
rm -f /tmp/convert_cookies.php
