#!/bin/bash

echo "🍪 JSON Cookie'lardan Netscape Format Fayl Yaratish"
echo "===================================================="
echo ""

cd ~/www/download.e-qarz.uz

COOKIES_DIR="storage/app/cookies"
mkdir -p "$COOKIES_DIR"

OUTPUT_FILE="$COOKIES_DIR/instagram_cookies.txt"

# JSON cookie'larni Netscape formatiga o'tkazish
cat > "$OUTPUT_FILE" << 'COOKIEEOF'
# Netscape HTTP Cookie File
# This file was generated by converting JSON cookies
# Generated: 2026-01-16

.instagram.com	TRUE	/	TRUE	1803132341	csrftoken	jVBDSeKkImhZpxb4ouQ6Gu
.instagram.com	TRUE	/	TRUE	1800791806	datr	_o5GaVPf72PeS7qlPEAZnWIl
.instagram.com	TRUE	/	TRUE	1776348341	ds_user_id	77052749976
.instagram.com	TRUE	/	TRUE	1797767806	ig_did	401ACE00-E9CA-420B-8108-7F984204377A
.instagram.com	TRUE	/	TRUE	1797767927	ig_nrcb	1
.instagram.com	TRUE	/	TRUE	1800791807	mid	aUaO_wALAAGex-IxWOC_WfUiAc5F
.instagram.com	TRUE	/	TRUE	1802832462	ps_l	1
.instagram.com	TRUE	/	TRUE	1802832462	ps_n	1
.instagram.com	TRUE	/	TRUE	0	rur	"LDC\05477052749976\0541800108343:01fe74ba91b85c587450a2846858e265f22669f735d018444b1f82eb349a5b2fbbcdc167"
.instagram.com	TRUE	/	TRUE	1800076266	sessionid	77052749976%3AUhHEDSDd8cLBTj%3A18%3AAYhmCvILE7LuKi-u8KQtgVROlM1MNgjJfNpF7Ve--g
.instagram.com	TRUE	/	TRUE	1769176879	wd	1920x963
COOKIEEOF

echo "✅ Cookie fayli yaratildi: $OUTPUT_FILE"
echo ""

# Tekshirish
echo "📋 Cookie faylini tekshirish:"
echo "----------------------------------------------------------"
echo ""

SIZE=$(stat -f%z "$OUTPUT_FILE" 2>/dev/null || stat -c%s "$OUTPUT_FILE" 2>/dev/null)
LINES=$(wc -l < "$OUTPUT_FILE" 2>/dev/null || echo "0")

echo "   Fayl hajmi: ${SIZE} bytes"
echo "   Qatorlar soni: ${LINES}"
echo ""

# Muhim cookie'larni tekshirish
if grep -q "sessionid" "$OUTPUT_FILE" 2>/dev/null; then
    echo "   ✅ sessionid topildi"
else
    echo "   ❌ sessionid topilmadi!"
fi

if grep -q "csrftoken" "$OUTPUT_FILE" 2>/dev/null; then
    echo "   ✅ csrftoken topildi"
else
    echo "   ⚠️  csrftoken topilmadi"
fi

if grep -q "ds_user_id" "$OUTPUT_FILE" 2>/dev/null; then
    echo "   ✅ ds_user_id topildi"
else
    echo "   ⚠️  ds_user_id topilmadi"
fi

echo ""
echo "📄 Faylning birinchi 5 qatori:"
head -5 "$OUTPUT_FILE"
echo ""

# Permissions
chmod 600 "$OUTPUT_FILE"
echo "✅ Permissions o'rnatildi (600)"
echo ""

echo "===================================="
echo "✅ Tugadi!"
echo ""
echo "📋 Keyingi qadamlar:"
echo "   1. Cookie faylini sozlash:"
echo "      chmod +x SETUP_MULTIPLE_COOKIES.sh"
echo "      ./SETUP_MULTIPLE_COOKIES.sh"
echo ""
echo "   2. Yoki tez sozlash:"
echo "      chmod +x QUICK_COOKIE_SETUP.sh"
echo "      ./QUICK_COOKIE_SETUP.sh"
echo ""
